### ISSUE TITLE
Where and how to write the path to the picture?

### ISSUE THREAD

**Issue by bezborodarnold** [daxslab/yii2-thumbnailer#1]
Hi. I installed your module yii2-thumbnailer. Where and how to write the path to the picture? I wrote so:

```
<div class="col-sm-6 col-md-4">
        <div `class="thumbnail">`
          <?php echo  Html::img(Yii::$app->thumbnailer->get($imageUrl)); $imageUrl='/web/images/kubiki.jpg';
?>
            <div class="caption">
                <h3>Task "Kub"</h3>
                <p>Content...</p>
                <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
            </div>
        </div>
    </div>
```
.  It doesn't work. How right?  I will have 6 elements and 6 pictures for them. Sorry, I'm a beginner in yii-2

**Comment by glpzzz** [comment]
Hi! To test, my suggestion is to do this:

<?= Html::img($imageUrl); ?>

If you can see the image in the large version, it means that it is no a URL issue. Then you can safely use:

Html::img(Yii::$app->thumbnailer->get($imageUrl));

I think you problem is with the URL you're using. Normally '/web' should not appear there. Try to write it as: 

$imageUrl = Yii::getAlias(@web/path/to/image.jpg);

This will ensure you're referencing files under you web visible path. 

Let me know if this works for you.
Best regards, g

**Comment by glpzzz** [comment]
Hey, can you tell me if the solution worked for you? If positive please, close the issue. Best regards, g
