### ISSUE TITLE
Thumbnailer generating url as file system path

### ISSUE THREAD

**Issue by davidmpaz** [daxslab/yii2-thumbnailer#11]
Hi 👋 !

thanks for the project. I am using now version 1.2.0 and my configuration in the `frontend` application looks like:

```
'thumbnailer' => [
            'class' => 'daxslab\thumbnailer\Thumbnailer',
            'thumbnailsBaseUrl' => '@web/assets/thumbnails',
            'enableCaching' => true,
],
```

One thing noticed is that the thumbnail directory is never generated. I created the directory with writable permissions and still nothing is written to it. I am using the thumbnailer as:

```
<?= Html::img(Yii::$app->thumbnailer->get('@web/img/default.jpg', 1000, 600), ['alt' => $defaultAlt]) ?>
```

I have checked the image url accessing directly to it so: `http://app-test.local/img/default.jpg` and i can load the image this way.

Having said this. When i check the image which is tried to being loaded is: 
`https://app-test.local/var/www/html/frontend/img/default.jpg`

Any idea on whats going wrong?

Thanks in advance,
David

**Comment by oatcpe** [comment]
in   Yii::$app->thumbnailer->get('@web/img/default.jpg'...

Please use full url path for image like Yii::$app->thumbnailer->get('http://test.com/img/default.jpg'...

**Comment by davidmpaz** [comment]
Thanks!
