### ISSUE TITLE
yii2-thumbnailer is making the application to load so slow

### ISSUE THREAD

**Issue by arunwebber** [daxslab/yii2-thumbnailer#3]
If i use this plugin the application is becoming very slow aka the image without thumbnail is much faster than that of thumbnail image

**Comment by cccaballero** [comment]
Enable the cache with enableCaching param. Sorry for the delay in answer.

**Comment by arunwebber** [comment]
> Enable the cache with enableCaching param. Sorry for the delay in answer.

How to do that?

**Comment by glpzzz** [comment]
When you are configuring the component in the configuration file:

'components' => [
...
[
'class' => Thumbnailer::class,
'enableCaching' => true
]
...
]
